SIM ?= ghdl
TOPLEVEL_LANG ?= vhdl

VHDL_SOURCES += /home/rayane/Desktop/risc_v_cpu/RISC_V_CPU/instruction_fetch/instruction_memory.vhd
COCOTB_TOPLEVEL = instruction_memory

# COCOTB_TEST_MODULES is the basename of the Python test file(s)
COCOTB_TEST_MODULES = if_testbench
include $(shell cocotb-config --makefiles)/Makefile.sim